import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Disruptive Management</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/disrup3.png" />
      </Head>

        <Navbar />
        <Hero />
    </>
  );
};

export default Home;
